### ISSUE TITLE
[FEATURE] Initialize files

### ISSUE THREAD

**Issue by LuckyPigeon** [LuckyPigeon/AnimeDrawingsDataset#1]
## Description

This is still an initialize project, and update files to version 1.0 is necessary.

## Tasks

- [x] Update `README.md`
- [x] Update `.gitignore`
- [x] Add `Gemfile`
- [x] Add `Rakefile`
- [x] Add `index.html`
- [x] Add `erb` directory and web pages
- [x] Add `js` directory and third-party `js` libraries
- [x] Add `rake` directory and third-party `ruby` libraries
- [x] Add `data` directory and datasets
